---
- name: update and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: install nginx
  apt:
    name: nginx

- name: download and unpack hugo
  unarchive:
    src: https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_extended_0.61.0_Linux-64bit.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: add let's encrypt repo
  apt_repository:
    repo: ppa:certbot/certbot

- name: install software-properties-common
  apt:
    name: software-properties-common

- name: install certbot
  apt:
    update_cache: yes
    name: python-certbot-nginx

