---
- name: create octetz group
  group:
    name: octetz
    state: present

- name: create octetz user
  user:
    name: octetz
    groups: 
    - octetz
    - sudo
    password: "{{ user_password }}"
    shell: /bin/bash

- name: add public keys
  authorized_key:
    user: octetz
    key: "{{ lookup('file', '{{ public_key_location  }}') }}"

